aluno/urls.py
from django.conf.urls import url
from aluno import views

urlpatterns = [
    url(r'^aluno/cadastro$', views.cadastro_aluno, name="cadastro-aluno"),
    url(r'^aluno/cadastrar$', views.cadastrar_aluno, name="cadastrar-aluno"),
    url(r'^aluno/pesquisa$', views.pesquisa_aluno, name="pesquisa-aluno"),
    url(r'^aluno/pesquisar$', views.pesquisar_aluno, name="pesquisar-aluno"),
    url(r'^aluno/(?P<aluno_id>\d+)/detalhe$', views.detalhe_aluno, name="detalhe-aluno"),
    url(r'^aluno/(?P<aluno_id>\d+)/edicao$', views.edicao_aluno, name="edicao-aluno"),
    url(r'^aluno/(?P<aluno_id>\d+)/editar$', views.editar_aluno, name="editar-aluno"),
    url(r'^aluno/(?P<aluno_id>\d+)/matricula$', views.matricula_aluno, name="matricula-aluno"),
    url(r'^aluno/(?P<aluno_id>\d+)/matricular$', views.matricular_aluno, name="matricular-aluno"),
	url(r'^aluno/(?P<aluno_id>\d+)/declaracao$', views.declaracao_aluno, name="declaracao-aluno"),
    url(r'^aluno/(?P<aluno_id>\d+)/declaracao/emitir$', views.emitir_declaracao_aluno, name="emitir-declaracao-aluno")

]  

escoladigital/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('aluno.urls')),
    url(r'^', include('escola.urls')),
    url(r'^', include('rendimento.urls')),
    url(r'^', include('historico.urls')),
    url(r'^', include('usuario.urls')),
    url(r'^', include('relatorio.urls')),
]
urlpatterns += staticfiles_urlpatterns()

historico/urls.py
from django.conf.urls import url
from historico import views

urlpatterns = [
    url(r'^historico/(?P<aluno_id>\d+)/cadastro$', views.cadastro_historico, name="cadastro-historico"),
  	url(r'^historico/(?P<aluno_id>\d+)/cadastrar$', views.cadastrar_historico),
  	url(r'^historico/(?P<aluno_id>\d+)/detalhe$', views.detalhe_historico, name='detalhe-historico'),
  	url(r'^historico/(?P<aluno_id>\d+)/emitir$', views.emitir_historico, name='emitir-historico'),
  	url(r'^historico/(?P<historico_id>\d+)/edicao$', views.edicao_historico, name='edicao-historico'),
	url(r'^historico/(?P<aluno_id>\d+)/consolidar$', views.consolidar_historico, name='consolidar-historico'),
  	url(r'^historico/editar$', views.editar_historico, name='editar-historico'),
	url(r'^historico/(?P<historico_id>\d+)/excluir$', views.excluir_historico, name='excluir-historico'),
  	url(r'^historico/instituicoes$', views.lista_instituicoes_historico)

]  

historico/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from escola.models import Serie, Disciplina
from aluno.models import Aluno
from simple_history.models import HistoricalRecords


class Instituicao(models.Model):

	descricao = models.CharField(max_length=255, null=False)
	cidade = models.CharField(max_length=255, null=False)
	uf = models.CharField(max_length=2, null=False)
	history = HistoricalRecords()

	class Meta(object):
		unique_together = ('descricao',)	

class Historico(models.Model):

	instituicao = models.ForeignKey(Instituicao)
	ano = models.PositiveIntegerField(null=False)
	carga_horaria = models.PositiveIntegerField(null=False)
	serie = models.ForeignKey(Serie)
	aluno = models.ForeignKey(Aluno, related_name='historicos')
	situacao = models.BooleanField(default=True)
	history = HistoricalRecords()

	class Meta(object):
		unique_together = ('ano','aluno')	

class Nota(models.Model):

	valor = models.DecimalField(max_digits=4, decimal_places=2)
	disciplina = models.ForeignKey(Disciplina, related_name='disciplina_historico')
	historico = models.ForeignKey(Historico, related_name='notas')
	history = HistoricalRecords()

historico/forms.py
# -*- coding: utf-8 -*-
from django import forms
import choices
from models import Historico
from escola.models import Serie


class HistoricoForm(forms.Form):
	ano = forms.ChoiceField(choices=choices.ANO_HISTORICO_CHOICES, required=True, error_messages={'required': 'Informe o ano corretamente.'})
	serie = forms.ModelChoiceField(queryset=Serie.objects.all(), required=True, error_messages={'required':'A série deve ser informada.'})
	situacao = forms.ChoiceField(choices=choices.SITUACAO_CHOICES, required=True, error_messages={'required': 'Informe a situação corretamente.'})
	uf = forms.ChoiceField(choices=choices.UF_CHOICES, required=True, error_messages={'required': 'Informe a situação corretamente.'})

historico/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from itertools import chain, groupby

from aluno.models import Aluno
from escola.models import Serie, Disciplina, Configuracoes
from escola import choices
from models import Historico, Nota, Instituicao
from historico.forms import HistoricoForm
from rendimento.choices import RECUPERACAO, RECUPERACAO_FINAL
import json
import numpy as np
from django.db import transaction
from util.utils import gerar_PDF, normal_round
from datetime import datetime



@login_required
def cadastro_historico(request, aluno_id):
	aluno = Aluno.objects.get(id=aluno_id)
	form = HistoricoForm()
	return render(request, 'cadastro-historico.html', {'aluno':aluno, 'form':form})


@login_required
@transaction.atomic
def cadastrar_historico(request, aluno_id):
	data = json.loads(json.loads(json.dumps(request.POST)).get('historico'))
	aluno = Aluno.objects.get(id=aluno_id)
	serie = Serie.objects.get(id=data['serie'])

	jsonInstituicao = data.get('instituicao')

	if jsonInstituicao.get('id'):
		instituicao =  Instituicao.objects.get(id=jsonInstituicao['id'])
	else:
		instituicao = Instituicao(descricao=jsonInstituicao['descricao'], uf=jsonInstituicao['uf'], cidade=jsonInstituicao['cidade'])
		instituicao.save()

	historico = Historico(instituicao=instituicao, situacao=data['situacao'], carga_horaria=data['carga'], serie=serie, ano=data['ano'], aluno=aluno)
	historico.save()
	for notaJSON in data.get('notas'):
		disciplina = Disciplina.objects.get(id=notaJSON['disciplina'])
		nota = Nota(disciplina=disciplina, valor=notaJSON['valor'], historico=historico)
		nota.save()

	return HttpResponse('{"sucess":true}', content_type='application/json')


@login_required
def detalhe_historico(request, aluno_id):
	aluno = Aluno.objects.get(id=aluno_id)
	return render(request, 'detalhe-historico.html', {'aluno':aluno, 'historicos':aluno.historicos.all()})


@login_required
def edicao_historico(request, historico_id):
	form = HistoricoForm()
	historico = Historico.objects.get(id=historico_id)
	return render(request, 'edicao-historico.html', {'form':form, 'aluno':historico.aluno, 'notas':historico.notas.all(), 'historico':historico})


@login_required
def excluir_historico(request, historico_id):
	form = HistoricoForm()
	historico = Historico.objects.get(id=historico_id)
	aluno = historico.aluno
	historico.delete()
	form.delete = True

	return render(request, 'detalhe-historico.html', {'form':form, 'aluno':aluno, 'historicos':aluno.historicos.all()})


@login_required
def lista_instituicoes_historico(request):
	data = json.loads(json.dumps(request.POST)).get('value')
	instituicoes = Instituicao.objects.filter(descricao__icontains=data)
	lista = serializers.serialize('json', instituicoes)
	return HttpResponse(lista, content_type='application/json')


@login_required
@transaction.atomic
def editar_historico(request):
	data = json.loads(json.loads(json.dumps(request.POST)).get('historico'))
	serie = Serie.objects.get(id=data['serie'])

	jsonInstituicao = data.get('instituicao')
	if jsonInstituicao.get('id'):
		instituicao = Instituicao.objects.get(id=jsonInstituicao['id'])
		instituicao.descricao = jsonInstituicao['descricao'] 
		instituicao.uf = jsonInstituicao['uf'] 
		instituicao.cidade = jsonInstituicao['cidade']
		instituicao.save()
	else:
		instituicao = Instituicao(descricao=jsonInstituicao['descricao'], uf=jsonInstituicao['uf'], cidade=jsonInstituicao['cidade'])
		instituicao.save()

	historico = Historico.objects.get(id=data['id_historico'])
	historico.situacao = data['situacao'] 
	historico.carga_horaria = data['carga']
	historico.serie = serie
	historico.instituicao = instituicao 
	historico.ano = data['ano']
	historico.save()

	for notaJSON in data.get('notas'):
		nota = Nota.objects.get(id=notaJSON['id'])
		nota.valor = notaJSON['valor']
		nota.save()

	return HttpResponse('{"sucess":true}', content_type='application/json')

@login_required
def emitir_historico(request, aluno_id):
	confs = Configuracoes.objects.get(id=1)
	aluno = Aluno.objects.get(id=aluno_id)
	disciplinas   = Disciplina.objects.all()
	series = Serie.objects.filter(modalidade=choices.MODALIDADE_FUNDAMENTAL)
	notas_historico = list(chain.from_iterable([historico.notas.all() for historico in aluno.historicos.all()]))

	for dis in disciplinas:
		dis.notas = np.full(9, None)
		notas_disciplina = [nota for nota in notas_historico if nota.disciplina.id == dis.id]
		for idx, serie in enumerate(series):
			nota = [nota for nota in notas_disciplina if nota.historico.serie.id == serie.id]
			if nota:
				dis.notas[idx] = nota[0]

	diversificada = filter(lambda x : not x.base_nacional_comum, disciplinas)
	base_nacional = filter(lambda x : x.base_nacional_comum, disciplinas)

	context = {'aluno':aluno,
	'confs':confs,
	'carga_horaria':get_carga_horaria(aluno, series),
	'historicos':aluno.historicos.all(),
	'rowspan_diversificada':len(diversificada) + 1, 
	'diversificada':diversificada, 
	'rowspan_base':len(base_nacional) +1, 
	'base_nacional':base_nacional,
	'data':datetime.now()}

	return gerar_PDF(request, context, 'template-historico-escolar-aluno', 'historico-'+aluno.nome)

	# return render(request, 'template-historico-escolar-aluno.html', context)

@login_required
def consolidar_historico(request, aluno_id):
	aluno = Aluno.objects.get(id=aluno_id)
	confs = Configuracoes.objects.get(id=1)
	matriculas = aluno.matriculas.filter(turma__serie__modalidade='F').exclude(ano=confs.ano_letivo)
	cbms = Instituicao.objects.get(id=1)
	for matricula in matriculas:
		historico = Historico.objects.filter(ano=matricula.ano, aluno=aluno)
		grupo_notas_disciplina = groupby(matricula.notas.all(), lambda x: x.disciplina)
		if historico:
			historico = historico[0]
			for key, value in grupo_notas_disciplina:
				notas = [nt for nt in value]
				nota = historico.notas.get(disciplina=key)
				nota.valor = get_nota_historico(notas)
				nota.save()

		else:
			historico = Historico(instituicao=cbms, situacao=True, carga_horaria=200, serie=matricula.turma.serie, ano=matricula.ano, aluno=aluno)
			historico.save()
			for key, value in grupo_notas_disciplina:
				notas = [nt for nt in value]
				valor = get_nota_historico(notas)
				if valor < confs.media and historico.situacao:
					historico.situacao=False
					historico.save()
				nota = Nota(disciplina=key, valor=valor, historico=historico)
				nota.save()
	
	return HttpResponse('{"sucess":true}', content_type='application/json')


def get_nota_historico(notas):
	
	rec_final = next(( n for n in notas if n.bimestre == long(RECUPERACAO_FINAL) and n.tipo == RECUPERACAO), None)
	
	medias_bimestrais = []
	
	for x, y in choices.BIMESTRE_CHOICES:	
		notas_bimestre = [n.valor for n in notas if n.bimestre == x and n.tipo != RECUPERACAO]
		nota_recuperacao = [n.valor for n in notas if n.bimestre == x and n.tipo == RECUPERACAO]
		media_bimestral = sum(notas_bimestre)/3
		medias_bimestrais.append(nota_recuperacao[0] if nota_recuperacao and nota_recuperacao[0] > media_bimestral else media_bimestral)

	return rec_final.valor if rec_final else normal_round(sum(medias_bimestrais)/4)


def get_carga_horaria(aluno, series):
	carga_horaria = np.full(9, None)

	for idx, serie in enumerate(series):
		carga_horaria[idx] = next(iter([historico.carga_horaria for historico in aluno.historicos.all() if historico.serie.id == serie.id]), None)

	return  carga_horaria

historico/templates/cadastro-historico.html
{% extends 'escoladigital/templates/base.html' %}


{% block message %}  

    <div class="alert alert-danger" id="alert-historico" style="display:none">
        Todos os campos do histórico devem ser preenchidos.
    </div>

    <div class="alert alert-success" id="alert-success" style="display:none">
      <button type="button" class="close">×</button>
        Histórico cadastrado com sucesso.       
    </div>

    <div class="alert alert-danger" id="alert-erro" style="display:none">
      <button type="button" class="close">×</button>
        Não foi possível salvar o histórico.   
    </div>

{% endblock message%}


{% block options %}

    {% include "include-opcoes-historico.html" %}

{% endblock options %}

{% block body %}
	
<form role="form">
  {% csrf_token %}
  <input type="hidden" id="aluno" value="{{aluno.id}}"> 
  <div class="panel panel-default">
      
      <div class="panel-heading">
        Cadastro De Histórico - {{aluno.nome}}
      </div>
      <div class="panel-body" >
      
      <div class="row">
        <div class="col-md-6">
          <label for="instituicao">Instituição</label>
          <input type="hidden" id="id_instituicao">
          <input type="text" class="form-control" id="desc_instituicao" name="desc_instituicao" >
        </div>
        <div class="form-group col-md-4">
          <label for="cidade">Cidade</label>
          <input type="text" class="form-control" id="cidade" name="cidade" >
        </div>
        
        <div class="form-group col-md-2">
          <label for="uf">UF</label>
          <select id="uf" name="uf" class="form-control" >
            <option>Selecione</option>
            {% for x, y in form.fields.uf.choices %} 
              <option value="{{x}}">{{y}}</option>
            {% endfor %}
          </select>   
        </div>

      </div>

      <div class="row">
        <div class="form-group col-md-3">
          <label for="ano">Ano</label>
          <select id="ano" name="ano" class="form-control" >
            <option value="">Selecione</option>
            {% for x, y in form.fields.ano.choices %} 
              <option value="{{x}}">{{y}}</option>
            {% endfor %}
          </select>   
        </div>

          <div class="form-group col-md-3">
          <label for="serie">Série</label>
          <select id="serie" name="serie" class="form-control" >
              <option value="">Selecione</option>
            {% for x in form.fields.serie.queryset %} 
              <option value="{{x.id}}">{{x.descricao}}</option>
            {% endfor %}
          </select>   
        </div>

        <div class="form-group col-md-2">
          <label for="ano">Carga Horária</label>
          <input type="text" class="form-control" id="carga" name="carga">
        </div>

          <div class="form-group col-md-3">
          <label for="situacao">Situação</label>
          <select id="situacao" name="situacao" class="form-control" >
              <option value="">Selecione</option>
            {% for x,y in form.fields.situacao.choices %} 
              <option value="{{x}}">{{y}}</option>
            {% endfor %}
          </select>   
        </div>

        </div>
    </div>
</div>  

<div class="panel panel-default">
           
    <div class="panel-heading">
      Disciplinas
    </div>
    
    <div class="panel-body" id="divDisciplinas">    

    </div>
</div>  
  
</form>

<script type="text/javascript">
  $(document).ready(function() {
    
    $("#serie").change(function(){
      $("#divDisciplinas").children().remove();
      $("#divDisciplinas").load("/escola/serie/"+$(this).val()+"/disciplinas/historico", function(){
          $(".number").mask('00.0', {'reverse':true});
      });
    });


    $("#desc_instituicao").autocomplete({
      source:function(request, response){
        $.ajax({
          type:'POST',
          headers: {'X-CSRFToken':$("input[name=csrfmiddlewaretoken]").val()},
          url: "/historico/instituicoes",
          data:{'value' : request.term}
        }).done(function(data){
            
            response($.map(data, function(item){
                      return{
                        label: item.fields.descricao,
                        id: item.pk,
                        uf: item.fields.uf,
                        cidade: item.fields.cidade
                      }
                  }
                )
              );
        });
     
      },
      
      select:function(event, ui){
        $("#cidade").val(ui.item.cidade);
        $("#uf").val(ui.item.uf);
        $("#id_instituicao").val(ui.item.id);
      },

      change: function( event, ui ) {
        if(ui.item == null){
          $("#cidade").val("");
          $("#uf").val("");
          $("#id_instituicao").val("");
        }
      }
    
    });

    $("#divDisciplinas").on('click','#btn-salvar', function(){
      if(validarCampos()){

          $.ajax({
            type:'POST',
            headers:{'X-CSRFToken':$("input[name=csrfmiddlewaretoken]").val()},
            url:'/historico/'+$("#aluno").val()+'/cadastrar',
            accept:'application/json',
            data:{'historico':JSON.stringify(montarObjetoHistorico())}
          }).done(function(response){
              if(response.sucess){
                $("#alert-success").show();
                $('html,body').scrollTop(0);
              }
              
          }).fail(function(){
              $("#alert-erro").show();
              $('html,body').scrollTop(0);
          });
      }

    });  
    
    $(".close").click(function(){
        $(this).parent().hide();
    });
    
    $("#carga").mask('00000000');

  });



  function validarCampos(){
    var pass = true
    $("input, select").not('input.number, :hidden').each(function(){
          if($(this).val() == "")
             pass = false
    });

    if(!pass){
      $("#alert-historico").show();
      $('html,body').scrollTop(0);
    }

    return pass;

  }

  function montarListaNotas(){
    var notas = [];
    $("#divDisciplinas table tbody tr").each(function(){
      var json = {
        "valor": $(this).find("input[type=text]").val(),
        "disciplina" :$(this).find("input[type=hidden]").val(),
      }
      notas.push(json);
    });
    return notas
  }

  function montarObjetoHistorico(){

    var json = {
      "instituicao":{ 'descricao':$("#desc_instituicao").val(),
                      'id':$("#id_instituicao").val(),
                      'cidade':$("#cidade").val(),
                      'uf':$("#uf").val()},
      "ano":$("#ano").val(),
      "serie":$("#serie").val(),
      "carga":$("#carga").val(),
      "situacao":$("#situacao").val(),
      "notas" : montarListaNotas()
    }

    return json;

  }

</script>

{% endblock body %}

historico/templates/detalhe-historico.html
{% extends 'escoladigital/templates/base.html' %}


{% block message %}  

{% if form.delete %}
  <div class="alert alert-warning" name="alert-historico">
    Historico excluido com sucesso.
  </div>
{% endif %}

    <div class="alert alert-danger" name="alert-historico" style="display:none">
        Todos os campos do histórico devem ser preenchidos.
    </div>

    <div class="alert alert-success" id="alert-success" style="display:none">
      <button type="button" class="close">×</button>
        Histórico cadastrado com sucesso.       
    </div>

    <div class="alert alert-success" id="alert-success-cons" style="display:none">
      <button type="button" class="close">×</button>
        Histórico consolidado com sucesso.       
    </div>

    <div class="alert alert-success" id="alert-success-err" style="display:none">
      <button type="button" class="close">×</button>
        Não foi possivel consolidar o histórico.    
    </div>

{% endblock message%}


{% block options %}
{% include "include-opcoes-historico.html" %}
{% endblock options %}

{% block body %}
	
<form role="form">
  {% csrf_token %}

  <div class="panel panel-default">
           
           <div class="panel-heading">
            <input type="hidden" id="aluno_id" value="{{aluno.id}}">
              Detalhe Histórico - {{aluno.nome}}
            </div>
           <div class="panel-body" >
            {% if  aluno.historicos %}
             
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th class="col-lg-5">Instituicão</th>
                    <th class="col-lg-1">Ano</th>
                    <th class="col-lg-2">Série</th>
                    <th class="col-lg-1">Situação</th>
                    <th class="col-lg-1"></th>
                    <th class="col-lg-1"></th>

                  </tr>
                </thead>
    
                <tbody>
                  {% for hs in historicos %} 
                    <tr>
                        <td class="col-lg-5">{{hs.instituicao.descricao}}</td>
                        <td class="col-lg-1">{{hs.ano}}</td>
                        <td class="col-lg-2">{{hs.serie.descricao}}</td>
                        
                        {% if hs.situacao %}
                          <td class="col-lg-1">Aprovado</td>  
                        {% else %}
                          <td class="col-lg-1">Reprovado</td>
                        {% endif %}
                        <td class="col-lg-1"><a href="{% url 'edicao-historico' hs.id %}"> Editar</a></td>
                        <td class="col-lg-1"><a href="{% url 'excluir-historico' hs.id %}"> Excluir</a></td>      
                    </tr>
                  {% endfor %}
                </tbody>

              </table>

            {% else %}

              <div class="alert alert-info">
                  Não existe histórico cadastrado para esse aluno.       
              </div>

            {% endif %}
          
            <button id="btn-consolidar" type="button" class="btn btn-primary">Consolidar Histórico</button>

    </div>
</div>  
  
</form>

<script type="text/javascript">
  $(document).ready(function() {

    $("#btn-consolidar").click(function(){

        $.ajax({
          type:'POST',
          headers: {'X-CSRFToken':$("input[name=csrfmiddlewaretoken]").val()},
          url:'/historico/'+$("#aluno_id").val()+'/consolidar',
          accept:'application/json'
        }).done(function(response){
            if(response.sucess){
              $("#alert-success-cons").show();
              $('html,body').scrollTop(0);

              setTimeout(function(){
                 location.reload()
              },3000)
            }
          
        }).fail(function(){
            $("#alert-erro-err").show();
            $('html,body').scrollTop(0);
        
        });

    });  
    
  });
</script>


{% endblock body %}

historico/templates/include-opcoes-historico.html
<div class="panel panel-default">
           
    <div class="panel-heading">
      Opções
    </div>
  
    <ul class="list-group">
      <li class="list-group-item"><a href="{% url 'detalhe-historico'  aluno.id %}">Detalhe Histórico</a></li>
      <li class="list-group-item"><a href="{% url 'cadastro-historico' aluno.id %}">Cadastro Histórico</a></li>        
      <li class="list-group-item"><a target="_new" href=" {% url 'emitir-historico' aluno.id %} ">Emitir Histórico</a></li>
    </ul>
  
  </div>